import {NgModule} from '@angular/core';

import {
  MenusPipe,
  FileSizePipe,
  KeysPipe,
  ThousandPipe,
  ExtensionPipe,
  BrPipe,
  ReformPipe,
  CategoryPipe,
  ScaleColor,
  TableHeadersPipe,
  TypeIconPipe,
  DataTypeIconPipe,
  BoxShadowPipe,
  GroupByPipe,
  TimeValuePipe,
  ContrastPipe,
  StateBackgroundPipe,
  ArrStrPipe,
  ColorsPipe,
  ThresPerPipe,
  TypeOperatorPipe,
  OperatorNamePipe,
  FieldListPipe,
  PushIndexPipe,
  MenuActivePipe,
  DatasetFilterPipe,
  FilterTypeOperatorPipe,
  SetTimePipe,
  filterOpPipe,
  GetTypePipe,
  ScheduleIntervalPipe,
  TypeOperatorFilterPipe,
  FieldTypePipe,
  LocalFilterPipe,
  // CompareFieldPipe,
  TypeOperatorStateFilterPipe,
  CheckXYZGroupPipe,
  FieldFilterPipe,
  CountTimePipe,
  IconNamePipe,
  DateKoreaForm,
  groupDepthPipe,
  timeDisabledPipe,
  CustomFilterList,

  DuplicationNamePipe,
  TextCamelCasePipe,
  indexColorPipe,
  DuplicationFieldNamePipe,
  FilterLengthPipe,
  DirectoryFilterPipe,
  FindFieldPipe,
  ComparisonTypePipe,
  FindTypePipe,
  GetFieldTypeofPipe,
  SplitTraceIdPipe,
  GradientColorsPipe,
  LegendIconPipe,
  UsedLengthPipe,
  SliderTrans,

} from './menus';
import {
  ListFilterPipe,
  SafeHtmlPipe
} from './filter';
import {SafePipe} from './safe';

import {
  NumeralFormatPipe,
  ThresholdFormatPipe
} from './number';
import {DateRangePipe, TimeForTodayPipe, TimePipe} from "./date";

export const PIPES = [
  MenusPipe,
  FileSizePipe,
  KeysPipe,
  ListFilterPipe,
  SafePipe,
  SafeHtmlPipe,
  ThousandPipe,
  ExtensionPipe,
  BrPipe,
  ReformPipe,
  CategoryPipe,
  ScaleColor,
  TableHeadersPipe,
  TypeIconPipe,
  DataTypeIconPipe,
  BoxShadowPipe,
  GroupByPipe,
  TimeValuePipe,
  ContrastPipe,
  StateBackgroundPipe,
  ArrStrPipe,
  ColorsPipe,
  ThresPerPipe,
  TypeOperatorPipe,
  OperatorNamePipe,
  FieldListPipe,
  PushIndexPipe,
  MenuActivePipe,
  DatasetFilterPipe,
  FilterTypeOperatorPipe,
  SetTimePipe,
  filterOpPipe,
  GetTypePipe,
  ScheduleIntervalPipe,
  TypeOperatorFilterPipe,
  FieldTypePipe,
  //CompareFieldPipe,
  TypeOperatorStateFilterPipe,
  CheckXYZGroupPipe,
  FieldTypePipe,
  LocalFilterPipe,
  FieldFilterPipe,
  CountTimePipe,
  IconNamePipe,
  DateKoreaForm,
  groupDepthPipe,
  timeDisabledPipe,
  CustomFilterList,
  NumeralFormatPipe,
  DuplicationNamePipe,
  TextCamelCasePipe,
  indexColorPipe,
  DuplicationFieldNamePipe,
  FilterLengthPipe,
  DirectoryFilterPipe,
  FindFieldPipe,
  ComparisonTypePipe,
  FindTypePipe,
  GetFieldTypeofPipe,
  SplitTraceIdPipe,
  GradientColorsPipe,
  LegendIconPipe,
  UsedLengthPipe,
  SliderTrans,
  ThresholdFormatPipe,
  SafeHtmlPipe,
  TimePipe,
  DateRangePipe,
  TimeForTodayPipe
];

@NgModule({
  declarations: PIPES,
  exports: PIPES
})
export class PipesModule {
}
